#
# Global environment options
#
# $Id: makefile.conf,v 1.18 2021/11/06 18:55:41 piru Exp $
#

MAKEFILENAME = makefile

TMPDIR       = /tmp/
INSTALLDIR   = /sys/
ARCHIVEDIR   = archives/
RELEASEDIR   = ambient_release/

PLATFORM     = morphos
PROCESSOR    = ppc

DEPFILE      = .depend.morphos

BUILDDIR     = objects

CPU_DEFAULT  = 750

HOSTCC       = gcc
HOSTLDFLAGS  =
HOSTCFLAGS   = -Wall -W -O2 -s -fomit-frame-pointer

CROSS_PREFIX = $(PROCESSOR)-$(PLATFORM)-

# bffunc_GATE generates wrong code without -fno-isolate-erroneous-paths-dereference.
# For same reason it thinks that passing NULL 'bm' to background_blit is invalid
# and replaces the code with crash if bm is NULL in bffunc_GATE. Avoid this by
# disabling this feature of the compiler. Throw the other similar options to the
# mix just to be safe. - Piru
CC           = $(CROSS_PREFIX)gcc-9 -fno-delete-null-pointer-checks -fno-isolate-erroneous-paths-dereference -fno-isolate-erroneous-paths-attribute
AS           = $(CROSS_PREFIX)as
LD           = $(CROSS_PREFIX)ld
AR           = $(CROSS_PREFIX)ar
NM           = $(CROSS_PREFIX)nm
RANLIB       = $(CROSS_PREFIX)ranlib
STRIP        = $(CROSS_PREFIX)strip
OBJCOPY      = $(CROSS_PREFIX)objdopy
OBJDUMP      = $(CROSS_PREFIX)objdump

CATMAKER     = ./catmaker
FLEXCAT      = flexcat
CVINCLUDE    = cvinclude.pl

DELETE       = rm -f
DELETEALL    = rm -rf
COPY         = cp
MKDIR        = mkdir -p
CONFIGTOOL   = ./ambientprefs

#
# please also try w/o no-sign-compare, this could be all *potential* bugs  (tokai) 
#
WARNINGS = -Wall -W -Wno-sign-compare -Wpointer-arith -Wstrict-prototypes\
		   -Wmissing-prototypes -Wmissing-declarations -Wnested-externs\
		   -Werror-implicit-function-declaration -Wcomments

#
# Issue 'make v=1' to get
# a verbose output
#
ifdef v
	ifeq ("$(origin v)", "command line")
		FANCYCOMPILE = 1
	endif
endif
ifndef FANCYCOMPILE
	FANCYCOMPILE = 0
endif

ifeq ($(FANCYCOMPILE), 0)
	OUT    = @
	ECHO   = @echo
	QUIET  = >/dev/null
	NODIR  = --no-print-directory
	SILENT = -s
else
	OUT    =
	ECHO   = @echo >/dev/null
	QUIET  =
	NODIR  =
	SILENT =
endif
