/*
 * Automatically generated by png2c
 *
 * $Id: def_view_logo.h,v 1.1 2026/01/25 17:39:37 kronos Exp $
 */


extern unsigned long def_view[];
#define DEF_VIEW_WIDTH 128
#define DEF_VIEW_HEIGHT 128
#define DEF_VIEW_DEPTH 32
